import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';
import { verifyToken } from '@/lib/jwt';
import { rateLimit } from '@/lib/rate-limit';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const supabaseServiceKey = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const supabase = createClient(supabaseUrl, supabaseServiceKey);

// Rate limit: 60 requests per minute per IP
const limiter = rateLimit({ windowMs: 60 * 1000, maxRequests: 60 });

/**
 * GET /api/stats
 * Returns aggregated productivity stats for the dashboard
 */
export async function GET(request: NextRequest) {
  const ip = request.headers.get('x-forwarded-for') || request.headers.get('x-real-ip') || 'unknown';
  const rateLimitResult = limiter(ip);

  if (!rateLimitResult.success) {
    return NextResponse.json(
      { error: 'Too many requests' },
      { status: 429, headers: {
        'X-RateLimit-Limit': '60',
        'X-RateLimit-Remaining': '0',
        'X-RateLimit-Reset': rateLimitResult.resetTime.toString(),
      }}
    );
  }

  try {
    // Authenticate via session cookie
    const sessionCookie = request.cookies.get('gitpulse_auth')?.value;
    if (!sessionCookie) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const sessionData = verifyToken(sessionCookie);
    if (!sessionData) {
      return NextResponse.json({ error: 'Invalid session' }, { status: 401 });
    }

    const { searchParams } = new URL(request.url);
    const period = searchParams.get('period') || '30'; // days
    const days = parseInt(period, 10);

    // Calculate date range
    const endDate = new Date();
    const startDate = new Date();
    startDate.setDate(endDate.getDate() - days);

    // Fetch all runs in period
    const { data: runs, error } = await supabase
      .from('telemetry_runs')
      .select('*')
      .eq('user_id', sessionData.userId)
      .gte('timestamp', startDate.toISOString())
      .lte('timestamp', endDate.toISOString())
      .order('timestamp', { ascending: true });

    if (error) {
      console.error('Failed to fetch runs for stats:', error);
      return NextResponse.json({ error: 'Failed to fetch stats' }, { status: 500 });
    }

    const runList = runs || [];

    // Calculate productivity stats
    const stats = calculateStats(runList, days);

    // Generate activity heatmap data
    const heatmap = generateHeatmap(runList, days);

    const response = NextResponse.json({ 
      stats,
      heatmap,
      period: {
        days,
        start: startDate.toISOString(),
        end: endDate.toISOString(),
      }
    });
    response.headers.set('X-RateLimit-Limit', '60');
    response.headers.set('X-RateLimit-Remaining', rateLimitResult.remaining.toString());
    response.headers.set('X-RateLimit-Reset', rateLimitResult.resetTime.toString());
    return response;

  } catch (error) {
    console.error('Stats API error:', error);
    return NextResponse.json({ error: 'Internal server error' }, { status: 500 });
  }
}

function calculateStats(runs: any[], days: number) {
  if (runs.length === 0) {
    return {
      totalCommits: 0,
      aiAssistedCommits: 0,
      manualCommits: 0,
      aiAssistedPercentage: 0,
      totalCommands: 0,
      avgQualityScore: 0,
      qualityPassRate: 0,
      totalIssuesCaught: 0,
      criticalIssuesCaught: 0,
      linesChanged: 0,
      filesChanged: 0,
      estimatedTimeSavedMinutes: 0,
      activeDays: 0,
      currentStreak: 0,
      longestStreak: 0,
    };
  }

  // Count commits by type
  let aiAssisted = 0;
  let manual = 0;
  let totalCommands = 0;
  let totalScore = 0;
  let passedCount = 0;
  let totalIssues = 0;
  let criticalIssues = 0;
  let linesChanged = 0;
  let filesChanged = 0;

  for (const run of runs) {
    // AI assisted if command_type exists (was generated by Pulse)
    if (run.command_type) {
      aiAssisted++;
      totalCommands++;
    } else {
      manual++;
    }

    totalScore += run.score;
    if (run.passed) passedCount++;
    totalIssues += run.total_issues || 0;
    criticalIssues += run.critical_issues || 0;
    linesChanged += run.lines_changed || 0;
    filesChanged += run.files_changed || 0;
  }

  const totalCommits = runs.length;
  const avgScore = Math.round(totalScore / totalCommits);
  const passRate = Math.round((passedCount / totalCommits) * 100);
  const aiPercentage = Math.round((aiAssisted / totalCommits) * 100);

  // Calculate streaks
  const { activeDays, currentStreak, longestStreak } = calculateStreaks(runs);

  // Estimate time saved: 2 minutes per AI-assisted commit
  const timeSaved = aiAssisted * 2;

  return {
    totalCommits,
    aiAssistedCommits: aiAssisted,
    manualCommits: manual,
    aiAssistedPercentage: aiPercentage,
    totalCommands,
    avgQualityScore: avgScore,
    qualityPassRate: passRate,
    totalIssuesCaught: totalIssues,
    criticalIssuesCaught: criticalIssues,
    linesChanged,
    filesChanged,
    estimatedTimeSavedMinutes: timeSaved,
    activeDays,
    currentStreak,
    longestStreak,
  };
}

function calculateStreaks(runs: any[]) {
  if (runs.length === 0) {
    return { activeDays: 0, currentStreak: 0, longestStreak: 0 };
  }

  // Group by date
  const dateMap = new Map<string, number>();
  for (const run of runs) {
    const date = new Date(run.timestamp).toISOString().split('T')[0];
    dateMap.set(date, (dateMap.get(date) || 0) + 1);
  }

  const dates = Array.from(dateMap.keys()).sort();
  const activeDays = dates.length;

  // Calculate streaks
  let currentStreak = 0;
  let longestStreak = 0;
  let currentCount = 0;
  let lastDate: Date | null = null;

  const today = new Date().toISOString().split('T')[0];
  const yesterday = new Date(Date.now() - 86400000).toISOString().split('T')[0];

  for (const dateStr of dates) {
    const date = new Date(dateStr);
    
    if (lastDate) {
      const diffDays = Math.floor((date.getTime() - lastDate.getTime()) / 86400000);
      if (diffDays === 1) {
        currentCount++;
      } else {
        longestStreak = Math.max(longestStreak, currentCount);
        currentCount = 1;
      }
    } else {
      currentCount = 1;
    }
    lastDate = date;
  }

  longestStreak = Math.max(longestStreak, currentCount);

  // Current streak (is today or yesterday in the dates?)
  const lastActiveDate = dates[dates.length - 1];
  if (lastActiveDate === today || lastActiveDate === yesterday) {
    // Count backwards from today/yesterday
    currentStreak = 0;
    const checkDate = new Date();
    if (lastActiveDate === yesterday) {
      checkDate.setDate(checkDate.getDate() - 1);
    }
    
    while (dateMap.has(checkDate.toISOString().split('T')[0])) {
      currentStreak++;
      checkDate.setDate(checkDate.getDate() - 1);
    }
  } else {
    currentStreak = 0;
  }

  return { activeDays, currentStreak, longestStreak };
}

function generateHeatmap(runs: any[], days: number) {
  // Group runs by date
  const dateMap = new Map<string, { count: number; intensity: number }>();
  
  const endDate = new Date();
  const startDate = new Date();
  startDate.setDate(endDate.getDate() - days);

  // Initialize all dates with 0
  for (let i = 0; i < days; i++) {
    const d = new Date(endDate);
    d.setDate(d.getDate() - i);
    const dateStr = d.toISOString().split('T')[0];
    dateMap.set(dateStr, { count: 0, intensity: 0 });
  }

  // Fill in actual data
  for (const run of runs) {
    const date = new Date(run.timestamp).toISOString().split('T')[0];
    if (dateMap.has(date)) {
      const current = dateMap.get(date)!;
      current.count++;
    }
  }

  // Calculate intensity levels (0-4)
  const maxCount = Math.max(...Array.from(dateMap.values()).map(d => d.count), 1);
  
  for (const [date, data] of dateMap) {
    if (data.count === 0) data.intensity = 0;
    else if (data.count <= maxCount * 0.25) data.intensity = 1;
    else if (data.count <= maxCount * 0.5) data.intensity = 2;
    else if (data.count <= maxCount * 0.75) data.intensity = 3;
    else data.intensity = 4;
  }

  // Convert to array format
  return Array.from(dateMap.entries()).map(([date, data]) => ({
    date,
    count: data.count,
    intensity: data.intensity,
  }));
}
