//! Response validation and parsing

use anyhow::{Result, anyhow};
use gitpulse_core::models::{CommitSuggestion, PRSuggestion, FileExplanation};

/// Parse commit response from AI
pub fn parse_commit_response(response: &str) -> Result<CommitSuggestion> {
    let message = response.trim().to_string();
    
    // Validate conventional commit format
    if !is_valid_commit(&message) {
        return Err(anyhow!("Invalid commit format: {}", message));
    }
    
    // Detect pattern
    let pattern = detect_pattern(&message);
    
    Ok(CommitSuggestion {
        message,
        confidence: 0.8, // TODO: Calculate based on model confidence
        pattern_detected: pattern,
        reasoning: vec!["Generated by AI".to_string()],
    })
}

/// Parse PR response from AI
pub fn parse_pr_response(response: &str) -> Result<PRSuggestion> {
    // Extract title (first line or ## Summary)
    let title = response.lines().next()
        .unwrap_or("Update")
        .to_string();
    
    // Extract body
    let body = response.to_string();
    
    // Extract summary
    let summary = extract_section(response, "Summary")
        .unwrap_or_else(|| response[..100.min(response.len())].to_string());
    
    Ok(PRSuggestion {
        title,
        body,
        summary,
        changes: vec![], // TODO: Parse from response
        testing_notes: vec![], // TODO: Parse from response
        related_issues: vec![], // TODO: Parse from response
    })
}

/// Parse file explanation response
pub fn parse_explain_response(response: &str) -> Result<FileExplanation> {
    let purpose = response.lines().next()
        .unwrap_or("Unknown purpose")
        .to_string();
    
    let history_summary = extract_section(response, "History")
        .unwrap_or_else(|| "No history available".to_string());
    
    let concerns = extract_bullet_points(response, "Concerns");
    
    Ok(FileExplanation {
        path: String::new(), // Set by caller
        purpose,
        history_summary,
        recent_changes: vec![],
        concerns,
    })
}

/// Check if commit message is valid
fn is_valid_commit(message: &str) -> bool {
    // Check conventional commit format: type(scope): description
    let re = regex::Regex::new(r"^(feat|fix|docs|style|refactor|perf|test|chore)(\([^)]+\))?: .+").unwrap();
    re.is_match(message)
}

/// Detect pattern from commit message
fn detect_pattern(message: &str) -> Option<String> {
    let lower = message.to_lowercase();
    
    if lower.contains("refactor") || lower.contains("simplify") {
        Some("refactor".to_string())
    } else if lower.contains("fix") || lower.contains("bug") {
        Some("fix".to_string())
    } else if lower.contains("add") || lower.contains("feat") {
        Some("feature".to_string())
    } else if lower.contains("test") {
        Some("test".to_string())
    } else if lower.contains("doc") {
        Some("docs".to_string())
    } else {
        None
    }
}

/// Extract section from markdown
fn extract_section(text: &str, section: &str) -> Option<String> {
    let pattern = format!(r"## {}\s*\n([^#]+)", regex::escape(section));
    let re = regex::Regex::new(&pattern).ok()?;
    
    re.captures(text)
        .and_then(|cap| cap.get(1))
        .map(|m| m.as_str().trim().to_string())
}

/// Extract bullet points from section
fn extract_bullet_points(text: &str, section: &str) -> Vec<String> {
    if let Some(content) = extract_section(text, section) {
        content.lines()
            .filter(|line| line.trim().starts_with('-') || line.trim().starts_with('*'))
            .map(|line| line.trim()[1..].trim().to_string())
            .collect()
    } else {
        vec![]
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn test_valid_commit() {
        assert!(is_valid_commit("feat(auth): add login functionality"));
        assert!(is_valid_commit("fix: resolve null pointer"));
        assert!(!is_valid_commit("invalid commit"));
    }
    
    #[test]
    fn test_detect_pattern() {
        assert_eq!(detect_pattern("feat: add new feature"), Some("feature".to_string()));
        assert_eq!(detect_pattern("fix: bug fix"), Some("fix".to_string()));
        assert_eq!(detect_pattern("refactor: simplify code"), Some("refactor".to_string()));
    }
}
